#
# taskset -c 79 ./fio -name=wrfiotest -filename=/data/wr/testfio.txt -direct=1 -iodepth=20 -thread -rw=randread -ioengine=libaio -bs=16k -size=5G -numjobs=2 -runtime=300 -group_reporting >> result.log
# taskset -c 79 ./fio testfio.job
#
[global]
filename=/data/wr/testfio.txt
bs=4k
thread
size=5G
runtime=300
group_reporting

[psync-read]
ioengine=psync
direct=0
iodepth=1
rw=read
stonewall

[psync-randread]
ioengine=psync
direct=0
iodepth=1
rw=randread
stonewall

[psync-write]
ioengine=psync
direct=0
iodepth=1
rw=write
stonewall

[psync-randwrite]
ioengine=psync
direct=0
iodepth=1
rw=randwrite
stonewall


[mmap-read]
ioengine=mmap
direct=1
iodepth=1
rw=read
stonewall

[mmap-randread]
ioengine=mmap
direct=1
iodepth=1
rw=randread
stonewall

[mmap-write]
ioengine=mmap
direct=1
iodepth=1
rw=write
stonewall

[mmap-randwrite]
ioengine=mmap
direct=1
iodepth=1
rw=randwrite
stonewall


[libaio-read]
ioengine=libaio
direct=1
iodepth=1
rw=read
stonewall

[libaio-randread]
ioengine=libaio
direct=1
iodepth=1
rw=randread
stonewall

[libaio-write]
ioengine=libaio
direct=1
iodepth=1
rw=write
stonewall

[libaio-randwrite]
ioengine=libaio
direct=1
iodepth=1
rw=randwrite
stonewall